# Generated by Django 4.2.7 on 2023-11-29 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='nomi',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='productId',
            new_name='maxsulotId',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='cost',
            new_name='soni',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='count',
            new_name='sotilganNarx',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='bio',
            new_name='haqida',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='kategoriya',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='count',
            new_name='kelganNarxi',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='minumSotishNarx',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='nomi',
        ),
        migrations.AddField(
            model_name='product',
            name='soni',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='sotishNarxi',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
    ]
