# Generated by Django 4.2.1 on 2024-01-02 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_product_img_alter_product_haqida'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
